In [1]:
import numpy as np

<h1>Assignment 1</h1>
<h3>Juan Camilo Castro Pinto</h3>
<h3>Andres Felipe Cantor</h3>
<br/>
2.

In [2]:
TD = np.array([[2, 3, 0, 3, 7], [0, 5, 5, 0, 3], [5, 0, 7, 3, 3], [3, 1, 0, 9, 9], [0, 0, 7, 1, 3,], [6, 9, 4, 6, 0]])
L = np.array([5,2,3,6,4,3])
print TD, L

[[2 3 0 3 7]
 [0 5 5 0 3]
 [5 0 7 3 3]
 [3 1 0 9 9]
 [0 0 7 1 3]
 [6 9 4 6 0]] [5 2 3 6 4 3]


$P(T,D) = P(T|D)P(D)$ 

$P(T,D) = \frac{TD_{i,j}}{\sum_{j} TD_{i,j}} * [\frac{1}{n}]$ 

$P(T,D) = $ $\frac{1}{n}$  [ $TD$ * diag($\frac{1}{[1]_{1xm} * TD}$) ]

In [3]:
def P_TD(TD):
    m, n = TD.shape
    suma = np.dot(np.ones((1,m)) ,TD)
    diag = np.diag(1/suma[0])
    p = (1.0/n) * np.dot(TD, diag)
    return p

P_TD(TD)
        
    

array([[0.025     , 0.03333333, 0.        , 0.02727273, 0.056     ],
       [0.        , 0.05555556, 0.04347826, 0.        , 0.024     ],
       [0.0625    , 0.        , 0.06086957, 0.02727273, 0.024     ],
       [0.0375    , 0.01111111, 0.        , 0.08181818, 0.072     ],
       [0.        , 0.        , 0.06086957, 0.00909091, 0.024     ],
       [0.075     , 0.1       , 0.03478261, 0.05454545, 0.        ]])

$P(T | D) = n * P(T,D)$

In [4]:
def P_T_D(TD):
    m,n = TD.shape
    return n * P_TD(TD)
P_T_D(TD)

array([[0.125     , 0.16666667, 0.        , 0.13636364, 0.28      ],
       [0.        , 0.27777778, 0.2173913 , 0.        , 0.12      ],
       [0.3125    , 0.        , 0.30434783, 0.13636364, 0.12      ],
       [0.1875    , 0.05555556, 0.        , 0.40909091, 0.36      ],
       [0.        , 0.        , 0.30434783, 0.04545455, 0.12      ],
       [0.375     , 0.5       , 0.17391304, 0.27272727, 0.        ]])

$P(D | T) = \frac{P(T,D)}{P(T,D) * [1]_{nx1}}$

In [5]:
def P_D_T(TD):
    m,n = TD.shape
    P_TD1 = P_TD(TD)
    P_T = np.dot(P_TD1, np.ones((n,1)))
    return P_TD1 / P_T
P_D_T(TD)

array([[0.17654612, 0.23539482, 0.        , 0.19259576, 0.3954633 ],
       [0.        , 0.45154704, 0.35338464, 0.        , 0.19506832],
       [0.35787437, 0.        , 0.34853851, 0.15616336, 0.13742376],
       [0.18524987, 0.05488885, 0.        , 0.40418153, 0.35567975],
       [0.        , 0.        , 0.64782097, 0.09675248, 0.25542655],
       [0.28373832, 0.37831776, 0.13158879, 0.20635514, 0.        ]])

$ P(D) = \frac{1}{n} * [1]_{1xn}$

In [6]:
def P_D(TD):
    m,n = TD.shape
    return 1.0/n * np.ones((1,n))
P_D(TD)

array([[0.2, 0.2, 0.2, 0.2, 0.2]])

$P(T) = P(T,D) * [1]_{nx1}$

In [7]:
def P_T(TD):
    m,n = TD.shape
    return np.dot(P_TD(TD), np.ones((n,1)))
P_T(TD)

array([[0.14160606],
       [0.12303382],
       [0.17464229],
       [0.20242929],
       [0.09396047],
       [0.26432806]])

$E[l] = L * P(T)$

In [8]:
def E_l(TD, L):
    return np.dot(L,P_T(TD))
E_l(TD, L)

array([3.86142666])

$Var(l) = \frac{1}{m} [ (L - E[l]) * (L - E[l])^T ]$

In [9]:
def var_l(TD, L):
    m,n = TD.shape
    expected = E_l(TD, L)
    return 1.0 / m * np.dot((L - expected), np.transpose((L - expected)))    

var_l(TD, L)

1.8063447904398182